
name: Deployment Flow

on:
  push:
    branches: ["main"]

jobs:
  
  deploy:
    name: Deploy to Heroku
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'
      
      #Obviously it won't work yet
      - name: Add remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      
      - run: git filter-branch -- --all
      
      - name: Deploy backend to heroku
        run: git push heroku HEAD:master -f
