name: Deployment Flow

on:
  push:
    branches: ["main"]

# .github/workflows/custom-deploy.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application to Digital Ocean
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} #IP address of the server to ssh
          key: ${{ secrets.SSH_KEY }} #Private or public key of server
          username: ${{ secrets.SSH_USERNAME }} #User of server to ssh into
          
          
          
          script: |
            cd ITProject-FiveFingers
            git pull
            cd client
            npm install -i
            npm run build
            cd ..
            npm install -i
            npm install pm2 -g
            pm2 delete all
            pm2 start server.js
            pm2 save --force
            pm2 restart all
          

