# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# Tells github when it triggers the job
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    defaults:
       run:
         working-directory: ./
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
        
  
    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        prettier: false
    - run: npm i
    # testing to run backend tests only
    # - run: npm run build --if-present
    # Go back to server to run backend tests
    # - run: cd ../
    - run: ${{ secrets.MONGO_URL_SED }}
    - run: npm test
